import { SectionLabel } from "./SectionLabel";

export function About() {
  return (
    <section
      id="about"
      className="mx-auto max-w-[1440px] px-6 py-24 md:px-10 md:py-32 lg:px-14"
    >
      <SectionLabel number="02">About</SectionLabel>

      {/* Editorial plate above the About narrative */}
      <figure
        className="mt-10 overflow-hidden border"
        style={{ borderColor: "var(--rule)", aspectRatio: "16 / 9" }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/assets/about-plate.jpg"
          alt="Editorial brutalist plate — architect's desk overhead view with tracing-paper diagrams, parametric shelter iso-plan, vermilion FIELD-VALIDATED stamp. Generated by fal.ai (Flux 2)."
          className="h-full w-full object-cover"
        />
        <figcaption
          className="flex items-baseline justify-between px-4 py-2"
          style={{
            background: "var(--paper)",
            borderTop: "1px solid var(--rule)",
            fontFamily: "var(--font-mono)",
            fontSize: "var(--fs-micro)",
            letterSpacing: "0.18em",
            textTransform: "uppercase",
            color: "var(--ink-3)",
          }}
        >
          <span>fig. 02 — about plate · fal.ai / flux-2</span>
          <span>Documentary still-life · 1024 × 576</span>
        </figcaption>
      </figure>

      <div className="mt-12 grid grid-cols-12 gap-6">
        <h2
          className="col-span-12 md:col-span-5"
          style={{
            fontFamily: "var(--font-display)",
            fontSize: "var(--fs-h1)",
            lineHeight: 1.05,
            letterSpacing: "-0.03em",
          }}
        >
          Four disciplines, one job.
        </h2>

        <div
          className="col-span-12 md:col-span-6 md:col-start-7 space-y-5"
          style={{ fontSize: "1.125rem", lineHeight: 1.65, color: "var(--ink-2)" }}
        >
          <p>
            The family business — <em>Rafik El-Khoury &amp; Partners</em>,
            founded in <strong>1967</strong> — is a consulting engineering
            practice with offices in Lebanon, Saudi Arabia, and Iraq, and
            remote project work across Africa. I grew up inside that story, so
            I went to <strong>Loughborough</strong> to study civil engineering.
          </p>
          <p>
            In my final year my dissertation on{" "}
            <strong>Natural Flood Management</strong> changed everything. It
            was the first time I saw the ecosystem as one connected system —
            where rivers, soils, vegetation, and human settlement are
            interlocking variables, and working <em>with</em> those connections
            produces better outcomes than working against them.
          </p>
          <p>
            I chased that thread. I took a{" "}
            <strong>Permaculture Design Course</strong>, volunteered on farms
            in Greece, and interned with an agricultural company — learning
            soil, plant taxonomy, and fungi from people who treat the ground as
            a living instrument rather than a substrate to pour concrete onto.
          </p>
          <p>
            That pulled me toward <strong>urbanism</strong>. At the{" "}
            <strong>University of Dundee</strong> I worked through a
            research-by-design masterplan on the city&apos;s urban-rural fringe
            — biophilic principles, master-planning fundamentals. I was honest
            with myself: the ideas were there, but the production tooling was
            slow.
          </p>
          <p>
            I went to <strong>Abu Dhabi</strong> to work with the family
            business — shadowing the urban designer on masterplans across the
            emirate, park briefs, villa redesigns, and a 19 km² island
            evaluation. Then back to <strong>Lebanon</strong>, where I
            contributed to concept design for roughly{" "}
            <strong>25 war-damaged schools</strong>, each rebuilt to its
            specific damage profile. The gap was unmistakable: the discipline
            needed faster, more data-driven tools.
          </p>
          <p>
            In <strong>September 2025</strong> I began a master&apos;s in{" "}
            <strong>AI for Architecture and the Built Environment</strong> at{" "}
            <em>IAAC</em>, Barcelona.
          </p>
          <p>
            I learned to code with AI as my pair — Claude Code, prompt
            engineering, the craft of giving context cleanly. In parallel I
            worked through <strong>computer vision</strong>,{" "}
            <strong>neural networks</strong>, and classical ML — so I could
            pick the right tool rather than the trendy one.
          </p>
          <p>
            <strong>This is where it all coheres.</strong> A multidisciplinary
            background — civil engineer, spatial planner, naturalist, family
            practice — finally inside a single identity: an engineer who
            leverages AI and computation to make the built-environment process
            more data-driven, more efficient, and more rigorous.
          </p>
        </div>
      </div>
    </section>
  );
}
