import { SectionLabel } from "./SectionLabel";

const credits: { role: string; tool: string; note: string }[] = [
  { role: "Framework", tool: "Next.js 16 (App Router)", note: "React 19, Turbopack." },
  { role: "Styling", tool: "Tailwind CSS v4", note: "@theme inline token bridge." },
  { role: "3D", tool: "React Three Fiber + drei + Three.js", note: "Per-project scenes, lazy-mounted." },
  { role: "Motion", tool: "GSAP + ScrollTrigger", note: "Pinned scrubs and section reveals." },
  { role: "Smooth scroll", tool: "Lenis", note: "Disabled under prefers-reduced-motion." },
  { role: "Image generation", tool: "fal.ai (Flux Pro + Flux Schnell)", note: "Hero plates and live regen demo." },
  { role: "Video", tool: "Remotion", note: "Intro reel and per-project sizzles, rendered to MP4." },
  { role: "Type", tool: "Newsreader + Archivo Black + Geist Mono", note: "Self-hosted via next/font/google." },
  { role: "Hosting", tool: "Cloudflare Pages", note: "Edge runtime; .pages.dev subdomain v1." },
  { role: "CV", tool: "RenderCV (engineering-resumes theme)", note: "Same data source as this site." },
  { role: "Orchestration", tool: "Claude Code · Opus 4.7", note: "Skill stack: frontend-design, industrial-brutalist-ui, gpt-taste, brandkit, impeccable." },
];

export function Colophon() {
  return (
    <section
      id="colophon"
      className="mx-auto max-w-[1440px] px-6 py-24 md:px-10 md:py-32 lg:px-14"
    >
      <SectionLabel number="05">Colophon</SectionLabel>

      <figure
        className="mt-10 overflow-hidden border"
        style={{ borderColor: "var(--rule)", aspectRatio: "16 / 9" }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/assets/colophon-plate.jpg"
          alt="Diagrammatic plate — isolines and contour curves of urban thermal comfort with vermilion accent markers. Generated by fal.ai (Flux 2)."
          className="h-full w-full object-cover"
        />
        <figcaption
          className="flex items-baseline justify-between px-4 py-2"
          style={{
            background: "var(--paper)",
            borderTop: "1px solid var(--rule)",
            fontFamily: "var(--font-mono)",
            fontSize: "var(--fs-micro)",
            letterSpacing: "0.18em",
            textTransform: "uppercase",
            color: "var(--ink-3)",
          }}
        >
          <span>fig. 05 — colophon plate · fal.ai / flux-2</span>
          <span>Diagrammatic · 1024 × 576</span>
        </figcaption>
      </figure>

      <h2
        className="mt-12 mb-3 max-w-[24ch]"
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "var(--fs-h1)",
          lineHeight: 1.05,
          letterSpacing: "-0.03em",
        }}
      >
        This site was built by orchestrated AI agents.
      </h2>
      <p
        className="mb-12 max-w-[68ch]"
        style={{ color: "var(--ink-2)", fontSize: "1.125rem", lineHeight: 1.6 }}
      >
        Every part of this site — copy drafts, the 3D scenes, the brutalist
        register, the live image regen — was produced by a stack of AI tools
        directed and reviewed by Rafik. The point of showing the stack is to
        make a claim explicit: <strong>orchestration</strong> is the
        differentiator, not any single model.
      </p>

      <div
        className="border-t"
        style={{ borderColor: "var(--rule)" }}
      >
        {credits.map((c, i) => (
          <div
            key={i}
            className="grid grid-cols-12 items-baseline gap-4 border-b py-4"
            style={{ borderColor: "var(--rule)" }}
          >
            <div
              className="col-span-3"
              style={{
                fontFamily: "var(--font-mono)",
                fontSize: "var(--fs-micro)",
                letterSpacing: "0.18em",
                textTransform: "uppercase",
                color: "var(--ink-3)",
              }}
            >
              {String(i + 1).padStart(2, "0")} · {c.role}
            </div>
            <div
              className="col-span-4"
              style={{
                fontFamily: "var(--font-display)",
                fontSize: "1.125rem",
                letterSpacing: "-0.01em",
                color: "var(--ink)",
              }}
            >
              {c.tool}
            </div>
            <div
              className="col-span-5"
              style={{ color: "var(--ink-2)", fontStyle: "italic" }}
            >
              {c.note}
            </div>
          </div>
        ))}
      </div>

      <div
        className="mt-12 flex flex-wrap items-baseline justify-between gap-4 border-t pt-6"
        style={{
          borderColor: "var(--rule)",
          fontFamily: "var(--font-mono)",
          fontSize: "var(--fs-micro)",
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          color: "var(--ink-3)",
        }}
      >
        <span>© Rafik El Khoury · 2026</span>
        <span>Source: github.com/elkhouryrafik-boop</span>
        <span>Tmrt is not a typo · It is the mean radiant temperature</span>
      </div>
    </section>
  );
}
