export function HeroPlate() {
  return (
    <figure
      className="relative w-full overflow-hidden border"
      style={{ borderColor: "var(--rule)", aspectRatio: "16 / 9" }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src="/assets/hero-plate.jpg"
        alt="Brutalist hero plate — concrete civic megastructure with faint Eixample diagram overlay in vermilion. Generated by fal.ai (Flux 2)."
        className="absolute inset-0 h-full w-full object-cover"
      />

      <figcaption
        className="absolute inset-x-0 bottom-0 flex items-baseline justify-between gap-4 p-4"
        style={{
          background: "color-mix(in oklab, var(--paper) 78%, transparent)",
          fontFamily: "var(--font-mono)",
          fontSize: "var(--fs-micro)",
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          color: "var(--ink-2)",
          borderTop: "1px solid var(--rule)",
        }}
      >
        <span>fig. 00 — hero plate · fal.ai / flux-2</span>
        <span style={{ color: "var(--ink-3)" }}>1600 × 900 · generated 2026</span>
      </figcaption>
    </figure>
  );
}
